/*
 * imu_lsm6ds.h
 *
 *  Created on: Nov 27, 2024
 *      Author: fsy13
 */

#ifndef INC_IMU_LSM6DS_H_
#define INC_IMU_LSM6DS_H_

#include <stdint.h>

typedef enum {
    RESERVED_00 = 0x00,
    FUNC_CFG_ACCESS,
    RESERVED_02,
    RESERVED_03,
    SENSOR_SYNC_TIME_FRAME,
    SENSOR_SYNC_RES_RATIO,
    FIFO_CTRL1,
    FIFO_CTRL2,
    FIFO_CTRL3,
    FIFO_CTRL4,
    FIFO_CTRL5,
    DRDY_PULSE_CFG_G,
    RESERVED_0C,
    INT1_CTRL,
    INT2_CTRL,
    WHO_AM_I,
    CTRL1_XL,
    CTRL2_G,
    CTRL3_C,
    CTRL4_C,
    CTRL5_C,
    CTRL6_C,
    CTRL7_G,
    CTRL8_XL,
    CTRL9_XL,
    CTRL10_C,
    MASTER_CONFIG,
    WAKE_UP_SRC,
    TAP_SRC,
    D6D_SRC,
    STATUS_REG,
    RESERVED_1F,
    OUT_TEMP_L,
    OUT_TEMP_H,
    OUTX_L_G,
    OUTX_H_G,
    OUTY_L_G,
    OUTY_H_G,
    OUTZ_L_G,
    OUTZ_H_G,
    OUTX_L_XL,
    OUTX_H_XL,
    OUTY_L_XL,
    OUTY_H_XL,
    OUTZ_L_XL,
    OUTZ_H_XL,
    SENSORHUB1_REG,
    SENSORHUB2_REG,
    SENSORHUB3_REG,
    SENSORHUB4_REG,
    SENSORHUB5_REG,
    SENSORHUB6_REG,
    SENSORHUB7_REG,
    SENSORHUB8_REG,
    SENSORHUB9_REG,
    SENSORHUB10_REG,
    SENSORHUB11_REG,
    SENSORHUB12_REG,
    FIFO_STATUS1,
    FIFO_STATUS2,
    FIFO_STATUS3,
    FIFO_STATUS4,
    FIFO_DATA_OUT_L,
    FIFO_DATA_OUT_H,
    TIMESTAMP0_REG,
    TIMESTAMP1_REG,
    TIMESTAMP2_REG,
    RESERVED_43,
    RESERVED_44,
    RESERVED_45,
    RESERVED_46,
    RESERVED_47,
    RESERVED_48,
    STEP_TIMESTAMP_L,
    STEP_TIMESTAMP_H,
    STEP_COUNTER_L,
    STEP_COUNTER_H,
    SENSORHUB13_REG,
    SENSORHUB14_REG,
    SENSORHUB15_REG,
    SENSORHUB16_REG,
    SENSORHUB17_REG,
    SENSORHUB18_REG,
    FUNC_SRC1,
    FUNC_SRC2,
    WRIST_TILT_IA,
    RESERVED_56,
    RESERVED_57,
    TAP_CFG,
    TAP_THS_6D,
    INT_DUR2,
    WAKE_UP_THS,
    WAKE_UP_DUR,
    FREE_FALL,
    MD1_CFG,
    MD2_CFG,
    MASTER_CMD_CODE,
    SENS_SYNC_SPI_ERROR_CODE,
    RESERVED_62,
    RESERVED_63,
    RESERVED_64,
    RESERVED_65,
    OUT_MAG_RAW_X_L,
    OUT_MAG_RAW_X_H,
    OUT_MAG_RAW_Y_L,
    OUT_MAG_RAW_Y_H,
    OUT_MAG_RAW_Z_L,
    OUT_MAG_RAW_Z_H,
    RESERVED_6C,
    RESERVED_6D,
    RESERVED_6E,
    RESERVED_6F,
    RESERVED_70,
    RESERVED_71,
    RESERVED_72,
    X_OFS_USR,
    Y_OFS_USR,
    Z_OFS_USR,
} imu_register_t;



// turn on the IMU
#define CTRL1_XL_HIGH_PERFORMANCE 0b00100000U
// enable the stepcounter algo , not the last 1 is for reseting the step count.
#define ENABLE_STEPCOUNTER 0b00010110U

//#define ENABLE_STEPDETECT_INTERRUPT 0b10000000U
//#define ENABLE_TAP_CFG 0b10001001U

void imu_lsm6ds_write_byte(imu_register_t register_address, uint8_t value);
uint8_t imu_lsm6ds_read_byte(imu_register_t register_address);

#endif /* INC_IMU_LSM6DS_H_ */
